### ISSUE TITLE
Scan stops in Dnscan 

### ISSUE THREAD

**Issue by ChennaiTechie** [iamthefrogy/frogy#14]
Enter the root domain name (eg: frogy.com):
google.com
Hold on! some house keeping tasks being done...
Creating google directory in the 'output' folder...
Identifying Subdomains
Is this program is in CHAOS dataset? (y/n)? n
connect: Connection refused
connect: Connection refused
Certificate search count: 315
Sublister count: 0
Findomain count: 56846
cat: output/google/dnstemp.txtls: No such file or directory
rm: cannot remove 'output/google/dnstemp.txtls': No such file or directory
Dnscan: 0

It stops in Dnscan:0 and stays there no progress sign

**Comment by ManojSharma1997** [comment]
I am having the same problem

**Comment by reedA201** [comment]
i have a Like the problem, what the solution?
