### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by gprime31** [iamthefrogy/frogy#19]

**Comment by gprime31** [comment]
![2022-01-06_21-00](https://user-images.githubusercontent.com/44535257/148479201-a2f3a556-0e71-4856-accc-994ab1a96e5b.png)

**Comment by gprime31** [comment]
not sure if this will affect anything.

**Comment by gprime31** [comment]
![2022-01-06_21-38](https://user-images.githubusercontent.com/44535257/148482550-9367f072-ee8a-43d7-b5f4-d12e35bc3ffb.png)

**Comment by iamthefrogy** [comment]
Hi Gp, can you DM me on Twitter please I want to ask a couple of questions? 

Twitter - https://twitter.com/iamthefrogy

**Comment by gprime31** [comment]
looks like your DM's are turned off
@PRIME31

**Comment by iamthefrogy** [comment]
I sent you an email, let's talk over there. You should have received an email from chintangurjar@outlook.com

**Comment by ManojSharma1997** [comment]
I am getting the same error.

**Comment by ManojSharma1997** [comment]
> looks like your DM's are turned off @prime31

How did you solve this issue?
