### ISSUE TITLE
ports to scan with naabu

### ISSUE THREAD

**Issue by molitona** [iamthefrogy/frogy#25]
Hi, I see that you use 106 ports to scan with naabu, is those the most used ones ?

Pls, if you have any source that includes most used ports by web apps send it to me

Thanks.

**Comment by iamthefrogy** [comment]
So I used Shodan's Facet analysis in order to identify the top 200 HTTP and HTTPS port. Then I de-dup them to create the one which is now in my script.

https://www.shodan.io/search/facet?query=http&facet=port
https://www.shodan.io/search/facet?query=https&facet=port
