### ISSUE TITLE
invalid flag in httpx -tech

### ISSUE THREAD

**Issue by m3hrajbhat** [iamthefrogy/frogy#9]
There is an invalid flag provided in httpx command: 
<httpx -silent -l output/$cdir/$cdir.master -p $portlst  -fr -include-chain -store-chain -sc **-tech** -server -title -cdn -cname -probe -srd output/$cdir/raw_http_responses -o output/$cdir/temp_live.txtls &> /dev/null>

replace with `-td `or `-tech-detect`

**Comment by iamthefrogy** [comment]
Done, I was using different version of httpx. Thanks for highlighting.
